# Generated by Django 5.2.7 on 2025-10-13 13:26

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Crime', 'Crime'), ('Thriller', 'Thriller'), ('Love', 'Love'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Fantasy', 'Fantasy')], max_length=61),
        ),
        migrations.AddField(
            model_name='item',
            name='streaming_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
