# Generated by Django 5.2.7 on 2025-10-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0002_item_genres_item_streaming_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
