# Generated by Django 5.2.7 on 2025-10-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0003_item_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='theatrical_experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Add YouTube link (full URL)', null=True),
        ),
    ]
